// Builds the showcase mix (`/demo`) from one real popflash evening:
// `npx tsx --env-file=.env.local backtest/demo-evening.ts` → lib/showcase/evening-2024-12-16.json. Owner's request (2026-09-25) to show the group a real example;
// a static page, never imported into any database (D25 still holds for the DB).
//
// Real: the ten players, the lineup they played, every map score and per-player line, and each
// player's engine input as of that evening (FACEIT history before it, earlier popflash maps as mix
// form). E is FACEIT ELO today (backtest assumption). Join times and votes are made up by the page.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { PlayerInput } from "@/lib/balance";
import { loadBacktestData } from "./data";
import { inputAt, lineRating } from "./evaluate";

const DAY = "2024-12-16";
const OWNER = "76561197993187687";
/** Keep FACEIT history this long before the evening (30-day window + baseline). */
const HISTORY_DAYS = 240;

const data = loadBacktestData();
const maps = data.matches.filter((m) => m.date.startsWith(DAY));
if (maps.length === 0) throw new Error(`No popflash maps on ${DAY}`);
const first = maps[0];
const at = new Date(first.date);
const earlier = data.matches.filter((m) => m.date < first.date);

const idOf = (popflashId: string) => {
  const id = data.steamIdOf.get(popflashId);
  if (!id) throw new Error(`Unknown popflash player ${popflashId}`);
  return id;
};
// Team A = the owner's team, the same five on every map (sides swap in popflash's team numbers).
const ownerTeam = (m: (typeof maps)[number]) =>
  m.players.find((l) => idOf(l.popflashId) === OWNER)!.team;
const teamOf = (m: (typeof maps)[number], team: number) =>
  m.players.filter((l) => l.team === team).map((l) => idOf(l.popflashId));
const teamA = teamOf(first, ownerTeam(first)).sort();
const everyone = first.players.map((l) => idOf(l.popflashId));
const teamB = everyone.filter((id) => !teamA.includes(id)).sort();
for (const m of maps) {
  const a = teamOf(m, ownerTeam(m)).sort();
  if (a.join() !== teamA.join()) throw new Error(`Lineup changed on ${m.id}`);
}

const prior = earlier.flatMap((m) =>
  m.players.filter((l) => l.rounds > 0).map(lineRating),
);
const groupRating = prior.length
  ? prior.reduce((s, x) => s + x, 0) / prior.length
  : null;

const since = at.getTime() - HISTORY_DAYS * 86_400_000;
const trim = (input: PlayerInput): PlayerInput => ({
  ...input,
  faceit: input.faceit && {
    matches: input.faceit.matches.filter(
      (s) => Date.parse(s.finishedAt) >= since,
    ),
  },
  activity: input.activity && {
    playedAt: input.activity.playedAt.filter((t) => Date.parse(t) >= since),
  },
});

const summaries = (
  JSON.parse(
    readFileSync(
      join(
        __dirname,
        "../lib/external/__fixtures__/steam/player-summaries.json",
      ),
      "utf8",
    ),
  ) as { response: { players: { steamid: string; avatarmedium: string }[] } }
).response.players;

async function avatarOf(steamId: string): Promise<string | null> {
  const known = summaries.find((p) => p.steamid === steamId)?.avatarmedium;
  if (known) return known;
  const key = process.env.STEAM_WEB_API_KEY;
  if (!key) return null;
  const r = await fetch(
    `https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=${key}&steamids=${steamId}`,
  );
  const body = (await r.json()) as {
    response: { players: { avatarmedium: string }[] };
  };
  return body.response.players[0]?.avatarmedium ?? null;
}

async function main() {
  const players = [];
  for (const steamId of everyone) {
    const f = data.faceit.get(steamId);
    const input = inputAt(steamId, at, data, earlier);
    if (!input || !f) throw new Error(`No FACEIT data for ${steamId}`);
    players.push({
      steamId,
      name: f.nickname,
      level: f.levelNow ?? 0,
      avatar: await avatarOf(steamId),
      input: trim(input),
    });
  }

  const title = (map: string) =>
    map.replace(/^de_/, "").replace(/^./, (c) => c.toUpperCase());
  const out = {
    $comment:
      "Generated by backtest/demo-evening.ts from the backtest fixtures (popflash evening + FACEIT history). Showcase page only (/demo), never imported into a database.",
    date: first.date,
    groupRating,
    teamA,
    teamB,
    players,
    maps: maps.map((m) => {
      const aTeam = ownerTeam(m);
      return {
        map: title(m.map),
        startedAt: m.date,
        a: aTeam === 1 ? m.score1 : m.score2,
        b: aTeam === 1 ? m.score2 : m.score1,
        lines: m.players.map((l) => ({
          steamId: idOf(l.popflashId),
          team: l.team === aTeam ? "A" : "B",
          k: l.kills,
          a: l.assists,
          d: l.deaths,
          adr: l.adr,
          rounds: l.rounds,
          rating: Math.round(lineRating(l) * 1000) / 1000,
        })),
      };
    }),
  };

  mkdirSync(join(__dirname, "../lib/showcase"), { recursive: true });
  const file = join(__dirname, `../lib/showcase/evening-${DAY}.json`);
  writeFileSync(file, JSON.stringify(out, null, 1) + "\n");
  console.log(
    `${file}: ${players.length} players, ${out.maps.length} maps, ${players.reduce((s, p) => s + (p.input.faceit?.matches.length ?? 0), 0)} FACEIT samples`,
  );
}

void main();
