// Balancing backtest (T-1): `npm run backtest` → backtest/REPORT.md. Method: backtest/README.md.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { resolveConfig } from "@/lib/balance";
import { loadBacktestData } from "./data";
import { evaluate, fitScale, models, type MapEval } from "./evaluate";
import {
  brier,
  calibration,
  favouriteWinRate,
  logLoss,
  spearman,
} from "./metrics";

const data = loadBacktestData();
const out: string[] = [];
const say = (line = "") => out.push(line);
const f = (x: number, d = 3) => (Number.isFinite(x) ? x.toFixed(d) : "–");
const pct = (x: number) =>
  Number.isFinite(x) ? `${(100 * x).toFixed(1)} %` : "–";
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length;
const median = (xs: number[]) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length % 2
    ? s[(s.length - 1) / 2]
    : (s[s.length / 2 - 1] + s[s.length / 2]) / 2;
};

/** Deterministic bootstrap of the log-loss difference (model − baseline) over maps. */
function bootstrapDelta(a: MapEval[], b: MapEval[], runs = 2000) {
  let seed = 42;
  const rnd = () => {
    seed = (seed * 1103515245 + 12345) % 2 ** 31;
    return seed / 2 ** 31;
  };
  const la = a.map((m) => logLoss([m.pred]));
  const lb = b.map((m) => logLoss([m.pred]));
  const deltas: number[] = [];
  for (let r = 0; r < runs; r++) {
    let s = 0;
    for (let i = 0; i < la.length; i++) {
      const k = Math.floor(rnd() * la.length);
      s += la[k] - lb[k];
    }
    deltas.push(s / la.length);
  }
  deltas.sort((x, y) => x - y);
  return {
    delta: mean(la) - mean(lb),
    lo: deltas[Math.floor(runs * 0.05)],
    hi: deltas[Math.floor(runs * 0.95)],
    better: deltas.filter((d) => d < 0).length / runs,
  };
}

const results = models().map((model) => ({
  model,
  ...evaluate(data, model.config),
}));
const base = results.find((r) => r.model.id === "elo")!;
const full = results.find((r) => r.model.id === "full")!;
const maps = full.maps;
const days = new Set(maps.map((m) => m.match.date.slice(0, 10)));

say("# Balancing backtest report");
say();
say(
  `Generated by \`npm run backtest\` from the popflash club history and the players' FACEIT history ` +
    `(test fixtures only, D25). Method and caveats: [README.md](README.md).`,
);
say();
say("## Data");
say();
say(
  `- Popflash maps: ${data.matches.length} (${data.matches[0].date.slice(0, 10)} … ${data.matches.at(-1)!.date.slice(0, 10)}).`,
);
say(
  `- Used: **${maps.length} maps** on ${days.size} evenings. Skipped: ${full.skipped.length}.`,
);
const reasons = new Map<string, number>();
for (const s of full.skipped)
  reasons.set(s.reason, (reasons.get(s.reason) ?? 0) + 1);
for (const [r, n] of reasons) say(`  - ${n} × ${r}`);
say(
  `- Team 1 won ${maps.filter((m) => m.pred.y === 1).length} of ${maps.length} used maps.`,
);
say();

say("## Which model predicts the winner best");
say();
say(
  "Log-loss and Brier: lower is better (coin flip = 0.693 / 0.250). *Fav. won*: how often the " +
    "team with the higher average S won. *Best k*: the Elo scale that would fit these maps best " +
    "(k = 1 is the standard 400-point curve). *Δ vs E only*: log-loss difference with a 90 % " +
    "bootstrap interval; negative = better than ELO alone. *S↔rating*: mean Spearman correlation " +
    "between a player's S and their Mixer Rating on that map (does S rank individual performance?).",
);
say();
say(
  "| Model | Log-loss | Brier | Fav. won | Best k (log-loss) | Δ vs E only [90 % CI] | P(better) | S↔rating |",
);
say("|---|---|---|---|---|---|---|---|");
for (const r of results) {
  const preds = r.maps.map((m) => m.pred);
  const fav = favouriteWinRate(preds);
  const fit = fitScale(r.maps);
  const d = r.model.id === "elo" ? null : bootstrapDelta(r.maps, base.maps);
  say(
    `| ${r.model.name} | ${f(logLoss(preds))} | ${f(brier(preds))} | ${pct(fav.rate)} (${fav.n}) | ` +
      `${f(fit.k, 2)} (${f(fit.logLoss)}) | ` +
      `${d ? `${f(d.delta, 4)} [${f(d.lo, 4)}, ${f(d.hi, 4)}]` : "–"} | ${d ? pct(d.better) : "–"} | ` +
      `${f(mean(r.maps.map((m) => m.skillVsRating).filter(Number.isFinite)), 2)} |`,
  );
}
say();

say("### Same models with a manual ELO of 1400 for players without FACEIT");
say();
say(
  "Players with no FACEIT account get a flat 1400, like a group admin's guess (D21). More maps, " +
    "noisier E.",
);
say();
say("| Model | Maps | Log-loss | Brier | Fav. won |");
say("|---|---|---|---|---|");
for (const model of models()) {
  const r = evaluate(data, model.config, { fallbackElo: 1400 });
  const preds = r.maps.map((m) => m.pred);
  const fav = favouriteWinRate(preds);
  say(
    `| ${model.name} | ${r.maps.length} | ${f(logLoss(preds))} | ${f(brier(preds))} | ${pct(fav.rate)} |`,
  );
}
say();

if (data.results.size > 0) {
  say("## ELO at the time of the map (rebuilt) vs ELO today");
  say();
  say(
    "E rebuilt by walking back from today's ELO over every later FACEIT queue match (±25 each, " +
      "`elo-history.ts`). Same maps, same everything else.",
  );
  say();
  say(
    "| Model | E | Log-loss | Brier | Fav. won | Best k | Δ rebuilt vs today [90 % CI] | P(better) |",
  );
  say("|---|---|---|---|---|---|---|---|");
  for (const model of models().filter((m) =>
    ["elo", "f-asym", "e-a", "no-a", "full"].includes(m.id),
  )) {
    const now = evaluate(data, model.config);
    const then = evaluate(data, model.config, { elo: "rebuilt" });
    for (const [label, r] of [
      ["today", now],
      ["rebuilt", then],
    ] as const) {
      const preds = r.maps.map((m) => m.pred);
      const fav = favouriteWinRate(preds);
      const d =
        label === "rebuilt" ? bootstrapDelta(then.maps, now.maps) : null;
      say(
        `| ${model.name} | ${label} | ${f(logLoss(preds))} | ${f(brier(preds))} | ${pct(fav.rate)} | ${f(fitScale(r.maps).k, 2)} | ` +
          `${d ? `${f(d.delta, 4)} [${f(d.lo, 4)}, ${f(d.hi, 4)}]` : "–"} | ${d ? pct(d.better) : "–"} |`,
      );
    }
  }
  say();
  const rebuilt = evaluate(data, full.model.config, { elo: "rebuilt" }).maps;
  const pairs = rebuilt.flatMap((m) =>
    [...m.team1, ...m.team2].map((p) => ({
      id: p.steamId,
      rebuilt: p.E,
      now: data.faceit.get(p.steamId)!.eloNow!,
      date: m.match.date,
    })),
  );
  say(
    "| Player | ELO today | Rebuilt, first used map | Rebuilt, last used map |",
  );
  say("|---|---|---|---|");
  const byPlayer = new Map<string, typeof pairs>();
  for (const x of pairs) byPlayer.set(x.id, [...(byPlayer.get(x.id) ?? []), x]);
  for (const [id, xs] of [...byPlayer].sort(
    (a, b) => b[1][0].now - a[1][0].now,
  )) {
    if (xs.length < 5) continue;
    say(
      `| ${data.nameOf.get(id) ?? id} | ${xs[0].now} | ${xs[0].rebuilt} (${xs[0].date.slice(0, 10)}) | ${xs.at(-1)!.rebuilt} (${xs.at(-1)!.date.slice(0, 10)}) |`,
    );
  }
  say();
  say(
    `Mean |today − rebuilt| over player-maps: ${f(mean(pairs.map((x) => Math.abs(x.now - x.rebuilt))), 0)} ELO.`,
  );
  say();
}

say("## Calibration (default model vs E only)");
say();
say(
  "| Favourite's predicted chance | Maps (default) | Predicted | Won | Maps (E only) | Predicted | Won |",
);
say("|---|---|---|---|---|---|---|");
const cf = calibration(full.maps.map((m) => m.pred));
const ce = calibration(base.maps.map((m) => m.pred));
cf.forEach((b, i) =>
  say(
    `| ${pct(b.from)} – ${pct(b.to)} | ${b.n} | ${pct(b.predicted)} | ${pct(b.actual)} | ` +
      `${ce[i].n} | ${pct(ce[i].predicted)} | ${pct(ce[i].actual)} |`,
  ),
);
say();

say("## How even were the real popflash teams");
say();
say(
  `Scored with the default model. Popflash teams were not balanced by any algorithm.`,
);
say();
say(
  `- Mean imbalance of the real lineups: **${f(mean(maps.map((m) => m.imbalance)), 1)} pp** ` +
    `(median ${f(median(maps.map((m) => m.imbalance)), 1)} pp, i.e. a ${f(50 + median(maps.map((m) => m.imbalance)), 1)} % favourite).`,
);
say(
  `- The engine's most even split for the same 10 players: mean ${f(mean(maps.map((m) => m.bestImbalance)), 2)} pp.`,
);
say(
  `- Median rank of the real lineup among the 126 splits: ${median(maps.map((m) => m.rank))}.`,
);
say(
  `- Maps where the real lineup was a clear mismatch (> 10 pp): ${maps.filter((m) => m.imbalance > 10).length}; ` +
    `the favourite won ${maps.filter((m) => m.imbalance > 10 && m.pred.p > 0.5 === (m.pred.y === 1)).length} of them.`,
);
say(
  `- Round difference vs predicted gap (Spearman): ${f(
    spearman(
      maps.map((m) => m.gap),
      maps.map((m) => m.roundDiff),
    ),
    2,
  )}.`,
);
say();

say("## What the terms did (default model)");
say();
const everyone = maps.flatMap((m) => [...m.team1, ...m.team2]);
const stat = (name: string, xs: number[]) =>
  say(
    `| ${name} | ${f(mean(xs.map(Math.abs)), 1)} | ${f(Math.min(...xs), 0)} | ${f(Math.max(...xs), 0)} | ${xs.filter((x) => x !== 0).length} of ${xs.length} |`,
  );
say("| Contribution | Mean abs. | Min | Max | Non-zero |");
say("|---|---|---|---|---|");
stat(
  "F (form)",
  everyone.map((s) => s.contributions.F),
);
stat(
  "M (mix form)",
  everyone.map((s) => s.contributions.M),
);
stat(
  "A (activity)",
  everyone.map((s) => s.contributions.A),
);
const status = new Map<string, number>();
for (const s of everyone)
  status.set(s.form.status, (status.get(s.form.status) ?? 0) + 1);
say();
say(
  `Form status per player-map: ${[...status].map(([k, n]) => `${k} ${n}`).join(", ")}. ` +
    `F hit its clamp ${everyone.filter((s) => s.form.clamped || s.form.rawClamped).length} times.`,
);
say();

say("## Per player: S vs how they actually played in the mixes");
say();
say(
  "Players with at least 5 used maps. *Mixer Rating* is Mixer Rating 2 from popflash stats with " +
    "popflash's real KAST. The last line is the Spearman correlation across players.",
);
say();
say("| Player | Maps | Mean S (default) | Mean E | Mixer Rating | Win % |");
say("|---|---|---|---|---|---|");
const per = new Map<
  string,
  { s: number[]; e: number[]; r: number[]; w: number[] }
>();
for (const m of maps) {
  for (const [team, won] of [
    [m.team1, m.pred.y === 1],
    [m.team2, m.pred.y === 0],
  ] as const)
    for (const p of team) {
      const x = per.get(p.steamId) ?? { s: [], e: [], r: [], w: [] };
      x.s.push(p.S);
      x.e.push(p.E);
      x.r.push(m.ratings.get(p.steamId)!);
      x.w.push(won ? 1 : 0);
      per.set(p.steamId, x);
    }
}
const rows = [...per]
  .filter(([, x]) => x.s.length >= 5)
  .sort((a, b) => mean(b[1].r) - mean(a[1].r));
for (const [id, x] of rows)
  say(
    `| ${data.nameOf.get(id) ?? id} | ${x.s.length} | ${f(mean(x.s), 0)} | ${f(mean(x.e), 0)} | ${f(mean(x.r), 2)} | ${pct(mean(x.w))} |`,
  );
say();
say(
  `Spearman(mean S, Mixer Rating) = ${f(
    spearman(
      rows.map(([, x]) => mean(x.s)),
      rows.map(([, x]) => mean(x.r)),
    ),
    2,
  )}; ` +
    `Spearman(mean E, Mixer Rating) = ${f(
      spearman(
        rows.map(([, x]) => mean(x.e)),
        rows.map(([, x]) => mean(x.r)),
      ),
      2,
    )}.`,
);
say();

say("## Sensitivity: weights grid");
say();
say(
  "Log-loss of the default model with other weights (rows: wF, columns: wM; wA = 1).",
);
say();
const wFs = [0, 0.5, 1, 1.5, 2];
const wMs = [0, 0.5, 1];
say(`| wF \\ wM | ${wMs.join(" | ")} |`);
say(`|---|${wMs.map(() => "---").join("|")}|`);
for (const wF of wFs) {
  const cells = wMs.map((wM) => {
    const r = evaluate(
      data,
      resolveConfig({
        weights: { elo: 1, faceitForm: wF, mixForm: wM, activity: 1 },
      }),
    );
    return f(logLoss(r.maps.map((m) => m.pred)));
  });
  say(`| ${wF} | ${cells.join(" | ")} |`);
}
say();

const path = join(__dirname, "REPORT.md");
writeFileSync(path, out.join("\n") + "\n");
console.log(out.join("\n"));
console.log(`\nWritten to ${path}`);
